# Generated by Django 4.0.3 on 2022-03-09 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('default_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='building',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomsection',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
