# Generated by Django 4.0.3 on 2022-03-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_alter_container_fixture_alter_container_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='fixture',
        ),
        migrations.AddField(
            model_name='container',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='container',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
