# Generated by Django 4.0.3 on 2022-03-10 03:00

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0008_alter_container_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': inventory.models.Container.saved_locations}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
