# Generated by Django 4.0.3 on 2022-03-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('inventory', '0019_remove_qrcode_container_qrcode_content_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='highvalue',
            old_name='item',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'container')), models.Q(('app_label', 'inventory'), ('model', 'article')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
