# Generated by Django 4.0.3 on 2022-03-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_item_article_rename_item_highvalue_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
