# Generated by Django 4.0.3 on 2022-03-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0021_rename_quanity_article_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'fixture')), models.Q(('app_label', 'inventory'), ('model', 'room')), models.Q(('app_label', 'inventory'), ('model', 'building')), models.Q(('app_label', 'inventory'), ('model', 'container'), ('name', 'Container')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
