# Generated by Django 4.0.3 on 2022-03-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0022_alter_article_content_type_alter_article_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'inventory'), ('model', 'fixture')), models.Q(('app_label', 'inventory'), ('model', 'room')), models.Q(('app_label', 'inventory'), ('model', 'building')), models.Q(('app_label', 'inventory'), ('model', 'container')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
